# This workflow should be called first and will cancel previously planned or running workflows
# The goal is to avoid running the same workflow twice reducing load on runners and risk of failure.
name: Cancel Workflow

# Controls when the action will run.
on:
  # Allows you to call this workflow from other workflows
  workflow_call:

jobs:
  cancel-runs:
    name: '🛑 Cancel Previous Runs'
    runs-on: ubuntu-latest

    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
