# This is workflow runs on PR
#
name: Checks

# Controls when the action will run.
on:
  # Trigger workflow for pull requests.
  pull_request:
    types: [opened, synchronize, reopened]

  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}_${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

# Declare default permissions as read only.
permissions:
  contents: read

jobs:
  lint-code:
    name: '▶️ actions'
    uses: ./.github/workflows/lint-code.yml
