# This is workflow runs on PR
#
name: Check

# Controls when the action will run.
on:
  # Trigger workflow for pull requests.
  pull_request:
    types: [opened, synchronize, reopened]

  push:
    branches: [main, alpha]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}_${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pr-lint:
    name: '▶️ actions'
    uses: ./.github/workflows/pr-lint.yml

  npm-lint:
    name: '▶️ actions'
    uses: ./.github/workflows/npm-lint.yml

  codeql:
    name: '▶️ actions'
    uses: ./.github/workflows/codeql.yml
