# This is the workflow to validate a PR
#
name: Lint Pull Request

on:
  # Allows you to call this workflow from other workflows
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint-pr:
    if: github.event_name == 'pull_request'
    name: '🕵️‍♂️ Lint Commit Message'
    runs-on: ubuntu-latest
    # container: node:lts-bullseye

    steps:
      # check for the most recent release: https://github.com/Namchee/conventional-pr/releases
      - name: '✅ Lint PR'
        uses: Namchee/conventional-pr@v0.15.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          label: '⁉️ invalid'
          branch_pattern: ''
